### ISSUE TITLE
Quieren seguirlo?

### ISSUE THREAD

**Issue by rlecaro2** [josencv/death-to-the-king#2]
Vi el updated 19 days ago y tengo la duda.

**Comment by josencv** [comment]
O sea, piola. Por ahora estoy haciendo pruebas con 3D para ver si es opción. Asi hay que dibujar un poco menos.

**Comment by rlecaro2** [comment]
mmm algún issue con `help wanted`?  O espero a que estés más resuelto?

**Comment by josencv** [comment]
Jaja, no hay nada en verdad... tengo un monito 3D que se mueve y que rota, pero sin animación. Como plus, se puede usar control de Xbox o teclado y además tiene música de fondo.

Mi plan de acción es investigar sobre cómo se trabaja el 3D en Unity y si veo que es una opción mejor (dado que con los dibujos nos ha ido mal), entonces de ahí planifico cómo seguir avanzando. Estás invitado a investigar también.

**Comment by rlecaro2** [comment]
Yo tenía pensado hacer mini juegos como pruebas de concepto con Phaser (que es para browsers). Voy a revisar lo que tenis y ... revisar más cosas pos.

**Comment by josencv** [comment]
El monito no está subido todavía. Por ahora sólo hay un cuadrado rojo que se mueve. Cuando pueda lo subo. Si quieres puedes hacerle un fork al proyecto para tener una base para partir algún otro juego de prueba que quieras hacer. (Aunque no es mucha base tampoco)
